# Build command
[build]

    # Source directory
    base = "."

    # Build file directory
    publish = "dist"

    # Build file command.
    command = "npm install && vite build && cp -r weeks dist"


[[edge_functions]]

    path = "/api/hello"
    function = "hello"