# Build command
[build]

    # Srource directory
    base = "src"

    # Build file directory
    publish = "dist"

    # Build file command.
    command = "npm install && npm run build && cp -r ../weeks dist && echo ls"


[[edge_functions]]

    path = "/api/hello"
    function = "hello"